# Generated by Django 4.0.6 on 2022-07-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=225)),
                ('student_number', models.IntegerField()),
                ('name', models.CharField(max_length=223)),
                ('isbn', models.IntegerField()),
                ('author', models.CharField(max_length=225)),
                ('category', models.CharField(max_length=225)),
                ('subject_area', models.CharField(max_length=20)),
                ('issue_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
    ]
